/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZustandTestRouteImport } from './routes/zustand-test'
import { Route as MswTestRouteImport } from './routes/msw-test'
import { Route as DbTestRouteImport } from './routes/db-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DbTestIdRouteImport } from './routes/db-test.$id'

const ZustandTestRoute = ZustandTestRouteImport.update({
  id: '/zustand-test',
  path: '/zustand-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MswTestRoute = MswTestRouteImport.update({
  id: '/msw-test',
  path: '/msw-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DbTestRoute = DbTestRouteImport.update({
  id: '/db-test',
  path: '/db-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DbTestIdRoute = DbTestIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DbTestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/db-test': typeof DbTestRouteWithChildren
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/db-test/$id': typeof DbTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/db-test': typeof DbTestRouteWithChildren
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/db-test/$id': typeof DbTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/db-test': typeof DbTestRouteWithChildren
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/db-test/$id': typeof DbTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/db-test' | '/msw-test' | '/zustand-test' | '/db-test/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/db-test' | '/msw-test' | '/zustand-test' | '/db-test/$id'
  id:
    | '__root__'
    | '/'
    | '/db-test'
    | '/msw-test'
    | '/zustand-test'
    | '/db-test/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DbTestRoute: typeof DbTestRouteWithChildren
  MswTestRoute: typeof MswTestRoute
  ZustandTestRoute: typeof ZustandTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zustand-test': {
      id: '/zustand-test'
      path: '/zustand-test'
      fullPath: '/zustand-test'
      preLoaderRoute: typeof ZustandTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msw-test': {
      id: '/msw-test'
      path: '/msw-test'
      fullPath: '/msw-test'
      preLoaderRoute: typeof MswTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-test': {
      id: '/db-test'
      path: '/db-test'
      fullPath: '/db-test'
      preLoaderRoute: typeof DbTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-test/$id': {
      id: '/db-test/$id'
      path: '/$id'
      fullPath: '/db-test/$id'
      preLoaderRoute: typeof DbTestIdRouteImport
      parentRoute: typeof DbTestRoute
    }
  }
}

interface DbTestRouteChildren {
  DbTestIdRoute: typeof DbTestIdRoute
}

const DbTestRouteChildren: DbTestRouteChildren = {
  DbTestIdRoute: DbTestIdRoute,
}

const DbTestRouteWithChildren =
  DbTestRoute._addFileChildren(DbTestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DbTestRoute: DbTestRouteWithChildren,
  MswTestRoute: MswTestRoute,
  ZustandTestRoute: ZustandTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
